version: '3'

services:

  go:
    build: .
    image: yuttasakcom/go-apis:1.0.0
    # environment:
    #   - PORT=80
    ports:
      - "8080:3000"
    restart: always

  mysql:
    image: mysql:5.7.21
    env_file:
      - .env
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always