version: '3.1'

services:

  go:
    build: .
    image: yuttasakcom/go-apis:1.0.1
    container_name: go
    ports:
      - "3000:3000"
    restart: always

  mysql:
    image: mysql:5.7.21
    container_name: mysql
    env_file:
      - .env
    volumes:
      - /data/mysql:/var/lib/mysql
    restart: always

  postgres:
    image: postgres:10.1
    container_name: postgres
    env_file:
      - .env
    volumes:
      - "/data/postgresql:/var/lib/postgresql"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
